# Default values for go-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kursadk/hpc-go
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

nameOverride: "go-app"
fullnameOverride: "go-app"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: go-app.co
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  # Specifies whether a service account should be created
  create: false

nodeSelector: {}

tolerations: []

affinity: {}
